### ISSUE TITLE
Response to Auth request should contain list of tables with access

### ISSUE THREAD

**Issue by andredaa** [CityScope/CS_CityIO#112]
We recently created new users that should have access to a dedicated table each (from shared google spreadsheet)

Upon authenticating as a user to cityIO: https://cityio.media.mit.edu/users/authenticate

I get the following response: 

{"id":29,"is_super":false,"tables":**[]**,"token":"4d47a64793d7a6a1d6660bc25866b483b3fc0cb1e24a9755a6e2119a93b5c860","user":"dahurian"}

the list of tables is empty. It should contain at least the table allocated in our google spreadsheet.

**Comment by yasushisakai** [comment]
ok will look into it

**Comment by yasushisakai** [comment]
it's working by design.

You need to initialize the table by putting 
```
"user": "username"
```
in the `header`. From that point, it will be a private table accessible only to that user and super users. I've made it the table in consideration private, so you will see the corresponding table appended in the result for the `/users/authenticate` api.

so the process to make a private table will be:

1.
```
curl -X POST -H 'username: {USERNAME}' -H 'password:{PASSWORD}' \
https://cityio.media.mit.edu/users/authenticate
```
and get the token

2.
```
curl -X POST -H 'Authorization: Baerer {THE_TOKEN}' \ 
-d '{"header":{"user":"{USERNAME}"}}' \
https://cityio.media.mit.edu/api/table/update/{TABLE_NAME}
```

while it's easy to reissue tokens, please try not to...
