### ISSUE TITLE
Local build documentation out of date

### ISSUE THREAD

**Issue by aberke** [CityScope/CS_CityIO#51]
I would like to build and run the CityIO backend locally.

It seems like the documentation (https://github.com/CityScope/CS_CityIO_Backend/wiki/Running-it-locally) was written for a node server but that the server is actually implemented in GoLang.  For example, `npm run build` does nothing without a `package.json` file at the root.

**Comment by tuxun** [comment]
install golang: `apt install golang-go`
get package:
`git clone https://github.com/mitmedialab/cityioserver --depth=1`
`cd cityioserver`
`go get .`
hum the shell shell cry because the app is not in $GOPATH env variable. (and print his value)
_got an idea taking a look in /home/user/go/src/github.com/CityScope/CS_CityIO_Backend:_
`cd /home/user/go/src/github.com/CityScope/CS_CityIO_Backend`
`go get .`
`./CS_CityIO_Backend `
`⇨ http server started on [::]:8080`

**Comment by agrignard** [comment]
@aberke  and @tuxun any update on this issue?

**Comment by aberke** [comment]
I haven't been taking any steps towards working on this.  I believe Yasushi is the assignee ;-)

**Comment by RELNO** [comment]
Note has been added to the page. Current version is in constant Dev mode and is running rust so page is anyway OOD.
Closing for now.
