### ISSUE TITLE
Difference between remote and local virtual table 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_CityIO#73]
Currently the local file https://github.com/CityScope/CS_CityIO_Backend/blob/master/examples/virtual_table.json (and all the link to this file in the wiki) is different from the one exposed on cityIO (https://cityio.media.mit.edu/api/table/virtual_table)

**Comment by RELNO** [comment]
different is ok, is the virtual brakes api?

**Comment by agrignard** [comment]
the virtual is now ok in term of pure API but different in the content from the local one even if they have the same name, which is quiet confusing for anyone trying to follow the documentation trying to undertand the format described in the wiki whoch is in link with the local one (especially the header, RL, RS, etc, etc...)

**Comment by RELNO** [comment]
the purpose of the VM virtual table is to be generic as possible not to impose types/block mappings. 
RL/RM etc are leftovers from very specific types used in certain CS projects.

**Comment by yasushisakai** [comment]
please clarify

A. all tables conforms [json object](https://www.w3schools.com/js/js_json_objects.asp)
otherwise the server will reject it. currently code wise this is only the requirement. (to also accommodate different json data, like sim results).

B. Yet, this issue is pointing that the current data does not abide the standard format shown in wiki. (I did not check)

therefore we have double standards which the architecture is loose than regulation. (*)

option 1. Do we want “cityio can take any json data” to hold true? because if the code restricts the data this claim will be negative. => action: leave it as is.

option 2. Do we want strict type checking, then we cannot say cityio has flexibility (except a no-mans area called `objects` prior than v1.10 ).

(*) like most cases

**Comment by RELNO** [comment]
At this point cityio takes any JSON as long as it's formatted, so that modules can send geojson/pure json. No plans to force any specific format in near future. Closing.
